In [2]:
import numpy as np

# 1 - dimensional array:
x = np.array([1, 2, 3, 4])
print ("1d array: ", x)

# 2 - dimensional array:
A = np.array([[1, 2], [3, 4], [5, 6]])
print ("2d array: ", A)

# Tranpose
A_t = A.T
print ("Transpose: ", A_t)

# We can see that A has 2 rows and 3 columns from A_t.
A_t.shape

1d array:  [1 2 3 4]
2d array:  [[1 2]
 [3 4]
 [5 6]]
Transpose:  [[1 3 5]
 [2 4 6]]


(2, 3)

In [3]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

print ("Vector row: ", vector_row)
print ("Vector column: ", vector_column)

Vector row:  [1 2 3]
Vector column:  [[1]
 [2]
 [3]]


In [9]:
# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
vector[2]

3

In [6]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [7]:
# Select everything up to and including the third element
vector[:3]


array([1, 2, 3])

In [8]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

review o'reilly page

In [11]:
# use numpy.matrix to create a matrix
matrix_object = np.mat([[1, 2],
                        [1, 2],
                        [1, 2]])

matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [12]:
# create a sparse matrix
from scipy import sparse

# create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print ("Sparse matrix: \n", matrix_sparse)

Sparse matrix: 
   (1, 1)	1
  (2, 0)	3


Sparse matrices only store nonzero elements and assume all other values will be zero, leading to significant computational savings.

In [16]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# View original sparse matrix
print(matrix_sparse)



  (1, 1)	1
  (2, 0)	3


In [17]:
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


That is, the addition of zero elements did not change the size of the sparse matrix.